// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bosstest/nexus-core/internal/domain (interfaces: WalletRepository,TransactionRepository,WalletCache,UnitOfWork,EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/mocks/repository_mock.go -package=mocks github.com/bosstest/nexus-core/internal/domain WalletRepository,TransactionRepository,WalletCache,UnitOfWork,EventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bosstest/nexus-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockWalletRepository is a mock of WalletRepository interface.
type MockWalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepositoryMockRecorder
	isgomock struct{}
}

// MockWalletRepositoryMockRecorder is the mock recorder for MockWalletRepository.
type MockWalletRepositoryMockRecorder struct {
	mock *MockWalletRepository
}

// NewMockWalletRepository creates a new mock instance.
func NewMockWalletRepository(ctrl *gomock.Controller) *MockWalletRepository {
	mock := &MockWalletRepository{ctrl: ctrl}
	mock.recorder = &MockWalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepository) EXPECT() *MockWalletRepositoryMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockWalletRepository) CreateWallet(ctx context.Context, wallet *domain.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockWalletRepositoryMockRecorder) CreateWallet(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockWalletRepository)(nil).CreateWallet), ctx, wallet)
}

// GetWalletByID mocks base method.
func (m *MockWalletRepository) GetWalletByID(ctx context.Context, id int64) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByID", ctx, id)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByID indicates an expected call of GetWalletByID.
func (mr *MockWalletRepositoryMockRecorder) GetWalletByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByID", reflect.TypeOf((*MockWalletRepository)(nil).GetWalletByID), ctx, id)
}

// GetWalletByIDForUpdate mocks base method.
func (m *MockWalletRepository) GetWalletByIDForUpdate(ctx context.Context, id int64) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByIDForUpdate indicates an expected call of GetWalletByIDForUpdate.
func (mr *MockWalletRepositoryMockRecorder) GetWalletByIDForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByIDForUpdate", reflect.TypeOf((*MockWalletRepository)(nil).GetWalletByIDForUpdate), ctx, id)
}

// GetWalletByUserID mocks base method.
func (m *MockWalletRepository) GetWalletByUserID(ctx context.Context, userID int64, currency string) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletByUserID", ctx, userID, currency)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletByUserID indicates an expected call of GetWalletByUserID.
func (mr *MockWalletRepositoryMockRecorder) GetWalletByUserID(ctx, userID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletByUserID", reflect.TypeOf((*MockWalletRepository)(nil).GetWalletByUserID), ctx, userID, currency)
}

// UpdateBalance mocks base method.
func (m *MockWalletRepository) UpdateBalance(ctx context.Context, wallet *domain.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockWalletRepositoryMockRecorder) UpdateBalance(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockWalletRepository)(nil).UpdateBalance), ctx, wallet)
}

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockTransactionRepository) CreateTransaction(ctx context.Context, tx *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionRepositoryMockRecorder) CreateTransaction(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).CreateTransaction), ctx, tx)
}

// GetByProviderTxID mocks base method.
func (m *MockTransactionRepository) GetByProviderTxID(ctx context.Context, providerID, providerTxID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProviderTxID", ctx, providerID, providerTxID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProviderTxID indicates an expected call of GetByProviderTxID.
func (mr *MockTransactionRepositoryMockRecorder) GetByProviderTxID(ctx, providerID, providerTxID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProviderTxID", reflect.TypeOf((*MockTransactionRepository)(nil).GetByProviderTxID), ctx, providerID, providerTxID)
}

// MockWalletCache is a mock of WalletCache interface.
type MockWalletCache struct {
	ctrl     *gomock.Controller
	recorder *MockWalletCacheMockRecorder
	isgomock struct{}
}

// MockWalletCacheMockRecorder is the mock recorder for MockWalletCache.
type MockWalletCacheMockRecorder struct {
	mock *MockWalletCache
}

// NewMockWalletCache creates a new mock instance.
func NewMockWalletCache(ctrl *gomock.Controller) *MockWalletCache {
	mock := &MockWalletCache{ctrl: ctrl}
	mock.recorder = &MockWalletCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletCache) EXPECT() *MockWalletCacheMockRecorder {
	return m.recorder
}

// AcquireHydrationLock mocks base method.
func (m *MockWalletCache) AcquireHydrationLock(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireHydrationLock", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireHydrationLock indicates an expected call of AcquireHydrationLock.
func (mr *MockWalletCacheMockRecorder) AcquireHydrationLock(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireHydrationLock", reflect.TypeOf((*MockWalletCache)(nil).AcquireHydrationLock), ctx, userID)
}

// InitCacheIfMissing mocks base method.
func (m *MockWalletCache) InitCacheIfMissing(ctx context.Context, userID int64, currency string, balance float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitCacheIfMissing", ctx, userID, currency, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitCacheIfMissing indicates an expected call of InitCacheIfMissing.
func (mr *MockWalletCacheMockRecorder) InitCacheIfMissing(ctx, userID, currency, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitCacheIfMissing", reflect.TypeOf((*MockWalletCache)(nil).InitCacheIfMissing), ctx, userID, currency, balance)
}

// PreProcess mocks base method.
func (m *MockWalletCache) PreProcess(ctx context.Context, op, providerID, providerTxID string, userID int64, currency string, amount float64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreProcess", ctx, op, providerID, providerTxID, userID, currency, amount)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreProcess indicates an expected call of PreProcess.
func (mr *MockWalletCacheMockRecorder) PreProcess(ctx, op, providerID, providerTxID, userID, currency, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreProcess", reflect.TypeOf((*MockWalletCache)(nil).PreProcess), ctx, op, providerID, providerTxID, userID, currency, amount)
}

// RefundAndUnlock mocks base method.
func (m *MockWalletCache) RefundAndUnlock(ctx context.Context, userID int64, currency, providerID, providerTxID string, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundAndUnlock", ctx, userID, currency, providerID, providerTxID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefundAndUnlock indicates an expected call of RefundAndUnlock.
func (mr *MockWalletCacheMockRecorder) RefundAndUnlock(ctx, userID, currency, providerID, providerTxID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundAndUnlock", reflect.TypeOf((*MockWalletCache)(nil).RefundAndUnlock), ctx, userID, currency, providerID, providerTxID, amount)
}

// ReleaseHydrationLock mocks base method.
func (m *MockWalletCache) ReleaseHydrationLock(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseHydrationLock", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseHydrationLock indicates an expected call of ReleaseHydrationLock.
func (mr *MockWalletCacheMockRecorder) ReleaseHydrationLock(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseHydrationLock", reflect.TypeOf((*MockWalletCache)(nil).ReleaseHydrationLock), ctx, userID)
}

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// DoTx mocks base method.
func (m *MockUnitOfWork) DoTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoTx indicates an expected call of DoTx.
func (mr *MockUnitOfWorkMockRecorder) DoTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoTx", reflect.TypeOf((*MockUnitOfWork)(nil).DoTx), ctx, fn)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishCompensationEvent mocks base method.
func (m *MockEventPublisher) PublishCompensationEvent(ctx context.Context, event *domain.CompensationEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCompensationEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCompensationEvent indicates an expected call of PublishCompensationEvent.
func (mr *MockEventPublisherMockRecorder) PublishCompensationEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCompensationEvent", reflect.TypeOf((*MockEventPublisher)(nil).PublishCompensationEvent), ctx, event)
}

// PublishTransactionCompleted mocks base method.
func (m *MockEventPublisher) PublishTransactionCompleted(ctx context.Context, event *domain.TransactionCompletedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTransactionCompleted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTransactionCompleted indicates an expected call of PublishTransactionCompleted.
func (mr *MockEventPublisherMockRecorder) PublishTransactionCompleted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTransactionCompleted", reflect.TypeOf((*MockEventPublisher)(nil).PublishTransactionCompleted), ctx, event)
}
